### ISSUE TITLE
save() overrides primary instead of updating object

### ISSUE THREAD

**Issue by osterbaer** [vicpinm/Kotlin-Realm-Extensions#23]
Hi,
so this is my class:

```
@AutoIncrementPK
open class Contact() : RealmObject() {
    @PrimaryKey
    var id: Long? = null
    var name: String = ""
    var publicKey: String = ""

    constructor(name: String, publicKey: String) : this() {
        this.name = name
        this.publicKey = publicKey
    }
}
```

I tried to do an update on an object like this:

```
contact.name = name
contact.save()
```

And instead of updating the object, a new object with these properties and new id is created. I checked the code and obviously the line initPk in save overrides the primary. I don't think that this is intended to happen, is it?

**Comment by vicpinm** [comment]
@osterbaer Well, actually that is intented to happen. I made that annotation for entities where you dont have a primary key value, and you need an autoincremental autogenerate pk. If you already have a pk, it is supposed that you dont need that annotation. Can you explain your use case with more details? Why do yoy need that annotation if you already have a PK?

**Comment by osterbaer** [comment]
Well yes I have a primary key and I want it to be autoincremental autogenerated. At first I used [this method](https://stackoverflow.com/questions/40174920/how-to-set-primary-key-auto-increment-in-realm-android) but when I saw your annotation I thought that this would not be necessary any more. But like explained above, it is not possible to update objects with your annotation at the moment because the primary key is always reset so that a duplicate with a new key is created.

**Comment by vicpinm** [comment]
@osterbaer I can check the primary key value, and only if is null, I can generate a pk for that entity. If not, I would keep the pk. Is that ok for your use case?

**Comment by osterbaer** [comment]
@vicpinm This would be perfect, thank you :)

**Comment by benjaminledet** [comment]
Hi @vicpinm , 
I'm facing de same issue, have you plan to add this feature soon?
Thanks.

**Comment by kvacquier** [comment]
Same here, bigs bugs while using own primary key with extension, is there a way to get the one you generate ? i mean, to identify the object and find it back in other activities

**Comment by vicpinm** [comment]
Hi @benjaminledet @kvacquier, I think I will be able to publish a new versión with the fix next week! Sorry for the waiting!

**Comment by vicpinm** [comment]
@benjaminledet @kvacquier @osterbaer 2.0.0 final version is published now, with the change in primary key generation. Now, only pk is auto generated if has null value.
