### ISSUE TITLE
Does not work anymore with Realm 4.0

### ISSUE THREAD

**Issue by mradzinski** [vicpinm/Kotlin-Realm-Extensions#24]
`RealmQuery.createQuery` in Realm 4.0 seems to be protected:

![screen shot 2017-10-19 at 3 05 38 pm](https://user-images.githubusercontent.com/4214209/31786489-0cee69b4-b4df-11e7-8255-15a30d15f439.png)

**Comment by vicpinm** [comment]
@mradzinski Hi, I haven't had time to see how it works with realm 4.0. I will try to do it next week. Thanks for the report!

**Comment by vicpinm** [comment]
Hi @mradzinski, you can now use version 2.0.0-beta1, which includes support for realm 4.0.

**Comment by mradzinski** [comment]
Awesome @vicpinm! Thanks!

![bitmoji](https://render.bitstrips.com/v2/cpanel/0c62d877-a0fb-4266-89d5-4d80ec96324f-b8fdcfdd-6cb5-4334-8636-fec5c4e11f8d-v1.png?transparent=1&palette=1&width=246)
