### ISSUE TITLE
Query error: "Overload resolution ambiguity"

### ISSUE THREAD

**Issue by erickssonxD** [vicpinm/Kotlin-Realm-Extensions#25]
**When trying to make a query that is not for a string, marks** 

```
Error:(128, 36) Overload resolution ambiguity:
public open fun equalTo(p0: String!, @Nullable p1: Byte?): RealmQuery<Notification!>! defined in io.realm.RealmQuery
public open fun equalTo(p0: String!, @Nullable p1: Int?): RealmQuery<Notification!>! defined in io.realm.RealmQuery
public open fun equalTo(p0: String!, @Nullable p1: Long?): RealmQuery<Notification!>! defined in io.realm.RealmQuery
public open fun equalTo(p0: String!, @Nullable p1: Short?): RealmQuery<Notification!>! defined in io.realm.RealmQuery
```

**This is the query**

```
Notification().queryAsObservable{
    query -> query.equalTo("status", 0)
}.subscribe { result ->
    //Do something
}
```

**Comment by vicpinm** [comment]
Hi @erickssonxD, I have tried your example in the sample proyect of this library and I dont get any compilation errors. I'm not sure what is the problem, maybe you can try with 0.toInt() to remove the ambiguity. But I think that is a good question for kotlin developers.

**Comment by magillus** [comment]
@erickssonxD what version of kotlin plugin you used

**Comment by vicpinm** [comment]
Hi @erickssonxD, I have created a new method, equalToValue(field, value), which does not have that problems. It seems to be a kotlin compiler related problem.
