### ISSUE TITLE
More than one file was found with OS independent path 'lib/x86/librealm-jni.so'

### ISSUE THREAD

**Issue by benjaminledet** [vicpinm/Kotlin-Realm-Extensions#27]
Hello,
I can't make your extension work, I've got this error when I build : 

Execution failed for task ':app:transformNativeLibsWithMergeJniLibsForDebug'.
> More than one file was found with OS independent path 'lib/x86/librealm-jni.so'

I tried to clean, rebuild but it still doesn't work.
It looks like a conflict but I really have no idea of how to solve it.
I tried with an all new empty project too (I just included all the libraries I use in my main project)

Edit  : I just saw  [this issue](https://github.com/vicpinm/Kotlin-Realm-Extensions/issues/18) an it does solve the problem but according to realm documentation : 

> Enabling Realm Mobile Platform: Before your application can synchronize with the Realm Object Server, it has to be enabled in your build file. Add this to the application’s build.gradle:
    realm {
      syncEnabled = true;
    }

 So this line is necessary to make object server work. So, can your extensions work with it?

This is my project gradle file : 

    // Top-level build file where you can add configuration options common to all sub-
    projects/modules.

    buildscript {
    ext.kotlin_version = '1.1.51'
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'io.realm:realm-gradle-plugin:4.1.1'
        classpath 'com.google.gms:google-services:3.0.0'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
    }

    allprojects {
    repositories {
        google()
        jcenter()
        maven { url "https://jitpack.io" }
    }
    }

    task clean(type: Delete) {
    delete rootProject.buildDir
    }

And my app gradle file : 

    apply plugin: 'com.android.application'

    apply plugin: 'kotlin-android'

    apply plugin: 'kotlin-android-extensions'

    apply plugin: 'kotlin-kapt'

    apply plugin: 'realm-android'

    android {
    compileSdkVersion 26
    defaultConfig {
        applicationId "com.ledet.benjamin.budgetmanager"
        minSdkVersion 21
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        def host = "118.121.198.145"
        debug {
            buildConfigField "String", "OBJECT_SERVER_IP", "\"${host}\""
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            buildConfigField "String", "OBJECT_SERVER_IP", "\"${host}\""
        }
    }
    dataBinding {
        enabled = true
    }
    }

    realm {
        syncEnabled = true
    }

    dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation"org.jetbrains.kotlin:kotlin-stdlib-jre7:$kotlin_version"
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'

    // Dependency for Google Sign-In
    compile 'com.google.android.gms:play-services-auth:11.6.0'

    // Dependency for Facebook Sign-in
    compile 'com.facebook.android:facebook-android-sdk:4.22.1'

    // Google support library
    compile 'com.android.support:cardview-v7:26.1.0'
    compile 'com.android.support:support-v4:26.1.0'
    compile 'com.android.support:customtabs:26.1.0'
    kapt "com.android.databinding:compiler:3.1.0-alpha02"

    //Anko
    compile 'org.jetbrains.anko:anko-commons:0.10.1'
    compile "org.jetbrains.anko:anko-design:0.10.1"

    //Realm
    compile "com.github.vicpinm:krealmextensions:2.0.0-beta1"

    //For Single and Flowable queries:
    compile 'io.reactivex.rxjava2:rxjava:2.1.5'
    compile 'io.reactivex.rxjava2:rxandroid:2.0.1'

    // Other libraries
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.github.lzyzsd:circleprogress:1.2.1'
    compile 'com.amulyakhare:com.amulyakhare.textdrawable:1.0.1'
    }

    apply plugin: 'com.google.gms.google-services'

**Comment by vicpinm** [comment]
Hi @benjaminledet, I have never used that feature of realm, so I can't say. I you need to make any changes to the library in order to make it work, you are welcome to make a PR. Thanks you so much.

**Comment by benjaminledet** [comment]
Hi @vicpinm ,
so the most convenient solution I found was adding this line :
`
compile("com.github.vicpinm:krealmextensions:2.0.0-beta2") {
        exclude module: 'realm-android-library'
    }
`
Indeed, considering that we are using the Realm module in our app, we don't need the one included in your library otherwise it's duplicated.
Maybe you can exclude the realm module when you're exporting the library?
Sorry I'm a bit of a beginner and I don't really know how to do this (and if it's a good way).

**Comment by vicpinm** [comment]
Hi @benjaminledet, I'm not sure if I cant do that. I see a main problem here: the library is made for a specific realm version, which is hardcoded in the library. If this version is not provided with the library, and you specific another different version, I can't say what could happen. But I will  think about it because maybe there is a better way to do this. 

Thanks you very much!
