### ISSUE TITLE
Support for RealmModule based objects in RealmConfigStore

### ISSUE THREAD

**Issue by magillus** [vicpinm/Kotlin-Realm-Extensions#29]
Current solution only supports RealmObject for definition of configuration.
We need to support also second way of creating Realm objects -> `@RealmClass` and `RealmModel interface` and `RealmModule`

**Comment by magillus** [comment]
It will be faster to do then expected - I will join it with #22

**Comment by vicpinm** [comment]
Hi @magillus, thanks alot for your PRs, I'm a bit busy these days but I will try to look at them as soon as I can!

**Comment by magillus** [comment]
@vicpinm I understand, I separated #29 from #22 which removed the dependency

**Comment by magillus** [comment]
I just noticed that this is not completed, it was overridden back because of reflection issues in commit 58ee7db5ff3a2292ca9698338c65f8e0059d5e14
