### ISSUE TITLE
Find this AND this query

### ISSUE THREAD

**Issue by damasofc** [vicpinm/Kotlin-Realm-Extensions#34]
I am using your extension, but I noticed that I want to do a AND query like this:
`RealmResults<Person> r1 = realm.where(Person.class)
                             .equalTo("dogs.name", "Fluffy")
                             .equalTo("dogs.color", "Brown")
                             .findAll();`

do you have a method to do this? or with the methods that are in your README, Can I do this?
I'll be grateful with your answer, thank you

**Comment by vicpinm** [comment]
Hi, have you tried this? 

    Person().query { it.equalTo("dogs.name", "Fluffy").equalTo("dogs.color", "Brown")  }

**Comment by damasofc** [comment]
Thank you, It works
