### ISSUE TITLE
Can't seem to use Migrations

### ISSUE THREAD

**Issue by easycheese** [vicpinm/Kotlin-Realm-Extensions#35]
Maybe I'm crazy but I can't figure out how to use your library and migrate the schema when I add a new Realm class.  All of your code appears to pull the default instance? 
 The only thing I can see is the sample:
```
        RealmConfigStore.init(User::class.java, userAddressConfig)
        RealmConfigStore.init(Address::class.java, userAddressConfig)
```

Does that mean if I use migrations I need to init for every class?  But you only use a single config (userAddressConfig) which makes it confusing.

**Comment by vicpinm** [comment]
Hi @easycheese, with RealmConfigStore.init you can specific differents realm configurations per model, but if you use the same realm configuration for all your entities, you don't need to specify that. By default, all entities uses the same realm default configuration. You can perform a migration as usual: 

    RealmConfiguration config = new RealmConfiguration.Builder(this)
                    .name("your_name")
                    .schemaVersion(X)
                    .migration(new Migrations())
                    .build();

**Comment by easycheese** [comment]
Here's the missing piece I needed:

`      Realm.setDefaultConfiguration(config)`

**Comment by vicpinm** [comment]
@easycheese I'm glad to hear that you have solve it
