### ISSUE TITLE
How to use QueryAllAsync?

### ISSUE THREAD

**Issue by damasofc** [vicpinm/Kotlin-Realm-Extensions#39]
Hi, I'm Using realm object server, but I want to know how it is used with sync, because in the README isn't anything about how to use it, Hope your answer, and thank you for your help.

**Comment by vicpinm** [comment]
Hi @damasofc, I have never used realm object server, I'm not sure if this library can help you. You are welcome to perform a PR if you want to add any new feature. Thanks you very much.
