### ISSUE TITLE
Please remove application params. from Manifest file 

### ISSUE THREAD

**Issue by sorinirimies** [vicpinm/Kotlin-Realm-Extensions#4]
I get several manifest file merge errors when trying to import the lib
Would it be possible to remove 
```
android:allowBackup="true" 
android:label="@string/app_name"
android:supportsRtl="true"
```

Are these actually needed, hence it's a library.

**Comment by SilkSama** [comment]
You can merge manually with tools:replace
https://developer.android.com/studio/build/manifest-merge.html

**Comment by vicpinm** [comment]
Sure, next version (1.0.6) won't include these params. It will be available today.
