### ISSUE TITLE
copyFromRealm as an option in FlowableExtensions

### ISSUE THREAD

**Issue by tgbarker** [vicpinm/Kotlin-Realm-Extensions#42]
On every request (most notably for Flowable<T>) the results are mapped using copyFromRealm

       result.asFlowable()
                .filter { it.isLoaded }
                .map { **realm.copyFromRealm(it)** }
                .subscribe({
                    subscriber.onNext(it)
                }, { subscriber.onError(it) })

This is certainly not desirable in every case and would be ideal to have the option to have a locally copied version of the objects or the managed realm backed version.

Consider the following example : 

class Parent : RealmObject() {
var id:String?=null
var children:RealmList<Child>?=RealmList<>()
}

class Child:RealmObject() {
var id:String?=null
}

If I use a function like queryAllAsFlowable() on the Parent.class and want to display the attribute "children" backed by changes in the DB as a Flowable<RealmList<T>> then this is not possible easily as it could be if the objects emitted were back by realm. If the objects emitted by the functions in RealmExtensionsFlowable were backed by Realm then I could simply do parent.children.asFlowable(). 

I could of course change the data model to make this work with the current lib, but it would be a shame.

Thank you for the lib in advance and hope I was clear?

**Comment by AndroFlo** [comment]
Thank you @tgbarker for this explanation.

**Comment by vicpinm** [comment]
Hi @tgbarker, what do you think if a create a new method like queryAllAsFlowable(managed = true/false)?

**Comment by tgbarker** [comment]
Hi @vicpinm ,

Sure I think that would be appropriate to be able to consequently feed performFlowableQuery managed=true/false as a parameter and avoid the copyFromRealm,

Thanks.

**Comment by vicpinm** [comment]
Hi  @tgbarker , version 2.1.1 is now available with this change.

**Comment by tgbarker** [comment]
Brilliant reactivity, thanks.
