### ISSUE TITLE
Query is inaccessible to RealmExtensionsKt

### ISSUE THREAD

**Issue by nikitagudkovs** [vicpinm/Kotlin-Realm-Extensions#44]
Hi! Thank you for the lib!
I'm having the following problem when I try to access my Realm Object:
`java.lang.IllegalAccessError: Method 'io.realm.RealmQuery io.realm.RealmQuery.createQuery(io.realm.Realm, java.lang.Class)' is inaccessible to class 'com.vicpin.krealmextensions.RealmExtensionsKt' (declaration of 'com.vicpin.krealmextensions.RealmExtensionsKt' appears in /data/app/ch.farmy.myApp-8cgk5W4ugikhcBaGovMlRw==/base.apk)`

**Comment by vicpinm** [comment]
Hi @nikitagudkovs, it seem to be something wrong with the dependencies, I have never seen this error before. Could you please provide your both build.gradle files from your app module and your top level project file?

**Comment by nikitagudkovs** [comment]
Hi @vicpinm , thank you for the quick response!

`apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'realm-android'
apply plugin: 'kotlin-kapt'
apply plugin: 'kotlin-android-extensions'

android {
    compileSdkVersion 27
    buildToolsVersion '26.0.2'
    defaultConfig {
        applicationId 'ch.farmy.fleetApp'
        minSdkVersion 21
        targetSdkVersion 27
        versionCode 12
        versionName "2.5 Languages"
        multiDexEnabled true
        vectorDrawables.useSupportLibrary = true

        javaCompileOptions {
            annotationProcessorOptions {
                includeCompileClasspath false
            }
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            zipAlignEnabled true
        }
    }
    compileOptions {
        targetCompatibility 1.8
        sourceCompatibility 1.8
    }
    productFlavors {
    }
}

dependencies {
    implementation 'com.google.firebase:firebase-core:11.8.0'
    implementation 'com.google.firebase:firebase-messaging:11.8.0'
    compile fileTree(include: ['*.jar'], dir: 'libs')
    //compile 'io.nlopez.smartlocation:library:3.2.0'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    testCompile 'junit:junit:4.12'
    implementation 'com.android.support:appcompat-v7:27.0.2'
    implementation 'com.android.support:design:27.0.2'
    implementation 'com.android.support:support-v4:27.0.2'
    implementation 'com.android.support:support-vector-drawable:27.0.2'
    // View binding with Butterknife
    implementation 'com.jakewharton:butterknife:8.8.1'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.8.1'
    // Reactive with rxjava
    implementation 'io.reactivex.rxjava2:rxandroid:2.0.1'
    implementation 'io.reactivex.rxjava2:rxjava:2.1.7'
    implementation 'com.squareup.retrofit2:adapter-rxjava2:2.3.0'
    // Gson
    compile 'com.google.code.gson:gson:2.8.1'
    // Retrofit
    //compile 'com.squareup.okhttp3:logging-interceptor:3.9.1'
    implementation 'com.squareup.retrofit2:retrofit:2.3.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.3.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:3.9.1'
    implementation 'com.squareup.retrofit2:adapter-rxjava:2.3.0'
    implementation 'com.android.support:cardview-v7:27.0.2'
    implementation 'com.android.support:multidex:1.0.2'
    implementation 'com.google.android.gms:play-services-location:11.8.0'
    implementation 'com.google.android.gms:play-services-analytics:11.8.0'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"

    //kapt 'groupId:artifactId:version'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jre7:$kotlin_version"

    implementation "com.google.android.gms:play-services-gcm:11.8.0"

    // reactive Preferences
    implementation 'com.f2prateek.rx.preferences2:rx-preferences:2.0.0-RC3'

    // realm extensions
    compile 'com.github.vicpinm:krealmextensions:1.0.4'
}

/*realm {
    syncEnabled = true
}*/
/** this line must always be at the bottom of the gradle file */
apply plugin: 'com.google.gms.google-services'
repositories {
    mavenCentral()
}`

and 

`// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext.kotlin_version = '1.2.21'
    repositories {
        jcenter()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
        classpath "io.realm:realm-gradle-plugin:4.3.1"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
        classpath 'com.google.gms:google-services:3.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:3.1.0'

    }
}

allprojects {
    repositories {
        jcenter()
        google()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
`

**Comment by nikitagudkovs** [comment]
<script src="https://gist.github.com/nikitagudkovs/82a66608a6faf1e0156088450a5167e0.js"></script>

**Comment by nikitagudkovs** [comment]
[top level](https://gist.github.com/nikitagudkovs/82a66608a6faf1e0156088450a5167e0)

**Comment by nikitagudkovs** [comment]
I tried creating realm objects in different ways and when I use .save() function there's no errors. But once I try to read with .first or .allItems app crashes with that error.

I've also noticed that there's no .queryFirst() in my dropdown

**Comment by vicpinm** [comment]
Hi @nikitagudkovs, the library version you are using is very old (1.0.4). Please update it to the last version 2.1.0. Also, notice the small breaking change that version has (see changelog for details).

**Comment by nikitagudkovs** [comment]
Hi @vicpinm . Thank you very much! Maybe you could update your article [here](https://antonioleiva.com/kotlin-realm-extensions/) to avoid confusion for others.
