### ISSUE TITLE
Type interface failure

### ISSUE THREAD

**Issue by nikitagudkovs** [vicpinm/Kotlin-Realm-Extensions#45]
Hi @ravidsrk 

I'm trying to work with queries and this is what I get at every attempt: 
<img width="700" alt="screen shot 2018-02-06 at 19 24 50" src="https://user-images.githubusercontent.com/33692877/35877100-a57c70ae-0b74-11e8-949c-ca79b2f4ebbe.png">

[Here's my class declaration](https://gist.github.com/nikitagudkovs/9d737b1881c925e5927ff2fee395276e).

Thank you in advance!

**Comment by vicpinm** [comment]
Hi @ravidsrk, sorry about that. In last version, queries doesn't receive anything in the lambda expression. So you should do: OrderData().delete { equalTo("id",1 }. The readme is not updated, I'm going to fix it. By the way, if you see an error in equalTo method like "overload resolution ambiguity", it happens in last realm versions, I'm not sure why. I have created a method equalToValue() for int and long types to avoid that error. You can use it if you see this error.

**Comment by nikitagudkovs** [comment]
Hi @vicpinm Thank you, OrderData().delete { equalTo("id",1 } is working.

Cheers!!
