### ISSUE TITLE
How have a result type OrderedRealmCollection

### ISSUE THREAD

**Issue by AndroFlo** [vicpinm/Kotlin-Realm-Extensions#46]
Hello, 

I use the RealmAdapter and i need to have an OrderedRealmCollection<T> to pass.

Is it possible with the library ?

Thank's

**Comment by vicpinm** [comment]
Hi  @AndroFlo, currently only flowable queries allow to specify the attribute managed = true, which returns a realmlist directly without calling to copyFromRealm() method. I have plans to add this option to other query methods, but currently methods like query() and queryAll() only return detached realm objects.

**Comment by yesidlazaro** [comment]
any news about this?
