### ISSUE TITLE
deleteAllManaged()

### ISSUE THREAD

**Issue by aguragorn** [vicpinm/Kotlin-Realm-Extensions#47]
This library is really handy.

Is there a way to delete all from a managed instance? kind of like when you call .saveAllManaged()
so I can delete only from the managed instance?

**Comment by vicpinm** [comment]
Hi @aguragorn, I'm afraid that functionality does not exists in the library. If you want, you can perform a PR and I will be pleased to merge it into master. 

Thanks you so much!
