### ISSUE TITLE
Param Query<T> ignored

### ISSUE THREAD

**Issue by cbedoy** [vicpinm/Kotlin-Realm-Extensions#48]
I'm using Realm Extensions but currently no all our code is on Kotlin we have several layers that will need to refactor (Java), I know extensions are not supported on java, that why I created like and Grapper on kotlin that recieve RealmQuery instead of Query

I'd like to know (if you know). How I can made the compatibility between Query<T> injected from  a java class as RealmQuery<T>.

I'm already know that you defined as 

```
public typealias Query<T>  = io.realm.RealmQuery<T>.() -> kotlin.Unit
```

Where I supposed if you inject a field as **RealmQuery<T>** should be supported, but seems like you library ignore my **RealmQuery<T>** injected cuz isn't a **Query<T>**

There's my example wrapper created in Kotlin it receive a class, fieldName, order and  *_query*

```
    override fun <T : RealmObject> querySortedObjects(_clazz: Class<T>, _fieldName: String, _order: Sort, _query: RealmQuery<T>): List<T> {
        val newInstance = _clazz.newInstance()
        val results = newInstance.querySorted(_fieldName, _order, {
            _query
        })

        Timber.d("$javaClass -> querySortedObjects: ${_clazz.javaClass} results: ${results.size}")

        return results
    }

   override  fun <T : RealmObject> queryByClass(_clazz: Class<T>): RealmQuery<T>? {
        return try {
            Realm.getDefaultInstance().where(_clazz)
        }catch (e : Exception){
            null
        }
    }


```
And there's my code provide from java.

```
    @Override
    public List<User> getFavorites(@NotNull String query) {

        RealmQuery<User> userRealmQuery = mRealmProvider.queryByClass(User.class);

        if (userRealmQuery != null){

            userRealmQuery.equalTo("favorite", true);

            if (query.length() > 0)
                userRealmQuery.and().contains("name", query, Case.INSENSITIVE);

            userRealmQuery.isNotNull("name");

            return mRealmProvider.querySortedObjects(User.class, "name", Sort.ASCENDING, userRealmQuery);
        }
        return new ArrayList<>();
    }
```

Seems ignore my **RealmQuery** param

<img width="952" alt="screen shot 2018-02-15 at 1 46 59 pm" src="https://user-images.githubusercontent.com/5570799/36277514-c0954abc-1256-11e8-9b6b-5fe7f66c08d6.png">

Then seems just perform this  
```

val results = newInstance.querySorted(_fieldName, _order)
```

**Comment by vicpinm** [comment]
Hi @cbedoy, you can call extensions functions from java without problems. Have you tried something like this?

    List<User> result =  RealmExtensionsKt.querySorted(new User(), "id", Sort.ASCENDING, new 
    Function1<RealmQuery<User>, Unit>() {
            @Override
            public Unit invoke(RealmQuery<User> query) {
                query.equalTo("field", "value");
                return Unit.INSTANCE;
            }
        });

And you can simplify this code if you use retrolambda.

**Comment by cbedoy** [comment]
Great! that works but my question is why seems my RealmQuery<<>> is ignored
```kotlin
override fun <T : RealmObject> querySortedObjects(_clazz: Class<T>, _fieldName: String, _order: Sort, _query: RealmQuery<T>): List<T> {
        val results = _clazz.newInstance().querySorted(_fieldName, _order, { 
            _query //this is ignored "The expression is unused"
        })
        return results
    }
```

**Comment by vicpinm** [comment]
@cbedoy You are trying to return an object inside the lambda. Lambda expression is defined as io.realm.RealmQuery<T>.() -> kotlin.Unit. As you can see, it returns Unit, so you can't return a query object.
