### ISSUE TITLE
Query throws exeption

### ISSUE THREAD

**Issue by uypanha** [vicpinm/Kotlin-Realm-Extensions#49]
Am I missing something? thanks :)

CartModel().queryFirst { it.equalsTo("_ID", 1) }
Method threw 'java.lang.ClassNotFoundException' exception.

this is my class
open class CartModel(
        @PrimaryKey open var _ID: Int = 0,
        open var qty: Int = 0,
        open var foodTitle: String = "",
        open var foodDes: String = "",
        open var price: String = "",
        open var previewURL: String = ""
) : RealmObject() {
    fun copy(
            _ID: Int = this._ID,
            qty: Int = this.qty,
            foodTitle: String = this.foodTitle,
            foodDes: String = this.foodDes,
            price: String = this.price,
            previewURL: String = this.previewURL
    ) = CartModel(_ID, qty, foodTitle, foodDes, price, previewURL)
}

**Comment by vicpinm** [comment]
Hi @uyphanha, with the information you have provided, I cant help you with your problem. If you are using last library version, you shouldn't use 'it' inside your lambda, just do:
     CartModel().queryFirst { equalsTo("_ID", 1) }

And make sure your realm version and library version match.

**Comment by uypanha** [comment]
I've fixed it, just changed it from CartModel().queryFirst { it.equalsTo("_ID", 1) } to CartModel().queryFirst { query -> query.equalsTo("_ID", 1) } and it works
