### ISSUE TITLE
Flowable not working when adding Consumer for subscription in subscribe

### ISSUE THREAD

**Issue by andrevdk** [vicpinm/Kotlin-Realm-Extensions#54]
Hello,

When queryAsFlowable, if I add Consumer for subscription in subscribe, the flowable doesn't work at all. I have to handle the subscription in doOnSubscribe in order to work. Is this normal behavior or a bug?

**Comment by vicpinm** [comment]
Hi @andrevdk, I have never used a Consumer object in my subscriptions, so I can't tell you where the problem is.  If you find any bug, you cand send a PR and I'll be pleased to merge it. 

Thanks you very much!
