### ISSUE TITLE
@linkingObject return always  null 

### ISSUE THREAD

**Issue by marwa1994** [vicpinm/Kotlin-Realm-Extensions#57]
i want to get the parent of specific object i have implemented this code

```
open class Parent() : RealmObject(){
  var steps: RealmList<Child>? =RealmList()}
```

and in Child

```
@LinkingObjects("steps")
    val parent: RealmResults<Parent>? = null
```
when i do this query `StepDataStore.getObject().query { equalTo("parent.id", id, Case.INSENSITIVE) } }`
i get always null

**Comment by vicpinm** [comment]
Hi, sorry for the delay. I'm not sure where the problem comes from, but i think is not a problem related with this library, but with realm and your model definition itself. Have you finally found where the problem comes from?

**Comment by Zat42** [comment]
Bump, I have the same problem.

Example:
```
open class Lesson(
    @PrimaryKey var id: String = "",
    @LinkingObjects("lessons")
    val sub_section: RealmResults<SubSection>? = null
}
```
This code works well, I can retrieve the lesson and the linked `sub_section`
```
        return realm.where(Lesson::class.java)
            .equalTo("id", lessonId)
            .findFirst()
```

This code successfully return the lesson but `sub_section` is null :
```
        return Lesson().queryFirst{ equalTo("id", lessonId) }
```
