### ISSUE TITLE
How to apply more than one condition on a realm model

### ISSUE THREAD

**Issue by FirdousNath** [vicpinm/Kotlin-Realm-Extensions#59]
Will below code work ?
```
val answerInfo = AnswerInfo().query {
                equalTo("test_id", testId)
                equalTo("saved", false)
            }
```

**Comment by vicpinm** [comment]
That code wont work, you need to create your queries as you do with realm. In your case:

    AnswerInfo().query {
                equalTo("test_id", testId). equalTo("saved", false)
            }
