### ISSUE TITLE
Accessing Kotlin Extension from Java

### ISSUE THREAD

**Issue by akbarsha03** [vicpinm/Kotlin-Realm-Extensions#6]
Do I have to always pass an object from Java to access the kotlin extenion like below?

```
final ChatConversationsRealm F = new ChatConversationsRealm();
List<ChatConversationsRealm> xx = RealmExtensionsKt.queryAll(F);
```

Is there any way to access it without creating an object but just by specifying the type like **RealmExtensionsKt.queryAll(ChatConversationsRealm.class)**?

**Comment by vicpinm** [comment]
I'm afraid it is not possible right now. You will need to create a new instance of your object to perform your query. I'm aware of this and I could find another way to perform the queries in the future if I have enough time. If you want to propose any solution, you are welcome to do a pull request.
