### ISSUE TITLE
Performance overhead

### ISSUE THREAD

**Issue by jegadeesan14mca** [vicpinm/Kotlin-Realm-Extensions#61]
I tried to use this library for my project. When I queried realm db via this library it returns "copyFromRealm" value. This will hardly affects the query performance.

Is there any way to get live Realm object with Realm instances management facility?

Thanks for this library. Let's rock realm world.

**Comment by magillus** [comment]
I think idea of this library to easy use the Realm on your "model" part of app, where you do DB/network on background thread.

**Comment by vicpinm** [comment]
Hi @jegadeesan14mca, currently that is not possible. If you really need this, you are welcome to do a PR, and I'll be please to merge to the project!
