### ISSUE TITLE
[Improvement request] Use doFinally

### ISSUE THREAD

**Issue by lemberh** [vicpinm/Kotlin-Realm-Extensions#63]
https://github.com/vicpinm/Kotlin-Realm-Extensions/blob/fbe7a34ac1c23313a5b451596a5eafe351190b48/library-base/src/main/java/com/vicpin/krealmextensions/RealmExtensionsFlowable.kt#L82
I recommend to use `doFinaly{}` instead of `doOnCancel{}` as then you can free resources also when the error happens

**Comment by vicpinm** [comment]
Hi @lemberh, thanks a lot, I'm going to try it and if it works, I will include it in the next release!

**Comment by vicpinm** [comment]
Just released version com.github.vicpinm:krealmextensions:2.5.0 with this change.
