### ISSUE TITLE
Perform Migration

### ISSUE THREAD

**Issue by saintjab** [vicpinm/Kotlin-Realm-Extensions#65]
Hi, I need a little help with realm migration For Kotlin. I know in Java after creating a migration class that extends from io.realm.ReamMigration, you can use the class as`realmConfiguration = RealmConfiguration.Builder()
                .schemaVersion(REALM_SCHEMA_VERSION)
                .migration(**new RealmMigration()**)
                .build()`
How can I do same in Kotlin, **new RealmMigration()** isn't working for me

**Comment by tamhuynhit** [comment]
in `Kotlin` there is no `new` keyword, only `YourCustomRealmMigration()` is enough (If it's what you're asking)

**Comment by saintjab** [comment]
Thanks for the help, that worked
