### ISSUE TITLE
RxJava2 support

### ISSUE THREAD

**Issue by mbarta** [vicpinm/Kotlin-Realm-Extensions#8]
Hey there, is there any plan to migrate to RxJava2 for your library? Currently, I'm getting conflicts during compilation when using RxJava2 and Kotlin-Realm-Extensions.

Thank you

**Comment by vicpinm** [comment]
Hi, yes I have plans to integrate rxJava2 as soon as I can (maybe during the next two weeks). If you need it earlier, you are welcome to do a pull request, and I will review it and merge into master.
